name: p2p_transfer
description: "A P2P file transfer application with E2E encryption"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for P2P transfer
  flutter_rust_bridge: ^2.0.0
  ffi: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  provider: ^6.1.1
  file_picker: ^8.0.0
  
  # UI enhancements
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.3.0
  percent_indicator: ^4.2.3
  
  # Networking
  web_socket_channel: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true
  
  # Assets for the app
  # assets:
  #   - assets/images/
  #   - assets/icons/
